### PR TITLE
Update StructLinq to 0.25.2

### LINKED ISSUE #10: Upgrade StructLinq
Hi @reegeek 
After a long pause away from OSS development, I'm trying to update the benchmarks.
I tried to upgrade StructLinq but it doesn't compile. The `uint` to `int` changes are easy to fix but I could not figure out what to do with the changes with `Where` and `Select` using `ref`.
Can you please submit a PR or simple give me some pointers?
Thanks

### PR DESCRIPTION
**Pull request by reegeek**
fix #10

### CODE REVIEW

**Comment by aalmada** [comment]
Sorry but for some reason, I thought there were more changes required. Thanks!

**Comment by reegeek** [comment]
In fact your right I must fix a bug in structLinq

**Comment by aalmada** [comment]
@reegeek I updated the benchmark results with the latest versions

**Comment by reegeek** [comment]
I saw yesterday. You did a very good job on hyperlink !

**Pull request merged**
